//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	apimachinerycache "github.com/kcp-dev/apimachinery/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v2"
	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	admissionregistrationv1listers "k8s.io/client-go/listers/admissionregistration/v1"
	"k8s.io/client-go/tools/cache"
)

var _ admissionregistrationv1listers.ValidatingWebhookConfigurationLister = &ValidatingWebhookConfigurationClusterLister{}

// ValidatingWebhookConfigurationClusterLister implements the admissionregistrationv1listers.ValidatingWebhookConfigurationLister interface.
type ValidatingWebhookConfigurationClusterLister struct {
	indexer cache.Indexer
}

// NewValidatingWebhookConfigurationClusterLister returns a new ValidatingWebhookConfigurationClusterLister.
func NewValidatingWebhookConfigurationClusterLister(indexer cache.Indexer) admissionregistrationv1listers.ValidatingWebhookConfigurationLister {
	return &ValidatingWebhookConfigurationClusterLister{indexer: indexer}
}

// List lists all admissionregistrationv1.ValidatingWebhookConfiguration in the indexer.
func (s ValidatingWebhookConfigurationClusterLister) List(selector labels.Selector) (ret []*admissionregistrationv1.ValidatingWebhookConfiguration, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*admissionregistrationv1.ValidatingWebhookConfiguration))
	})
	return ret, err
}

// Get retrieves the admissionregistrationv1.ValidatingWebhookConfiguration from the indexer for a given name.
func (s ValidatingWebhookConfigurationClusterLister) Get(name string) (*admissionregistrationv1.ValidatingWebhookConfiguration, error) {
	panic("Calling 'Get' is not supported before scoping lister to a workspace")
}

// Cluster returns an object that can list and get admissionregistrationv1.ValidatingWebhookConfiguration.

func (s ValidatingWebhookConfigurationClusterLister) Cluster(cluster logicalcluster.Name) admissionregistrationv1listers.ValidatingWebhookConfigurationLister {
	return &ValidatingWebhookConfigurationLister{indexer: s.indexer, cluster: cluster}
}

// ValidatingWebhookConfigurationLister implements the admissionregistrationv1listers.ValidatingWebhookConfigurationLister interface.
type ValidatingWebhookConfigurationLister struct {
	indexer cache.Indexer
	cluster logicalcluster.Name
}

// List lists all admissionregistrationv1.ValidatingWebhookConfiguration in the indexer.
func (s ValidatingWebhookConfigurationLister) List(selector labels.Selector) (ret []*admissionregistrationv1.ValidatingWebhookConfiguration, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*admissionregistrationv1.ValidatingWebhookConfiguration)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}

	return ret, err
}

// Get retrieves the admissionregistrationv1.ValidatingWebhookConfiguration from the indexer for a given name.
func (s ValidatingWebhookConfigurationLister) Get(name string) (*admissionregistrationv1.ValidatingWebhookConfiguration, error) {
	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(admissionregistrationv1.Resource("ValidatingWebhookConfiguration"), name)
	}
	return obj.(*admissionregistrationv1.ValidatingWebhookConfiguration), nil
}
