//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	apimachinerycache "github.com/kcp-dev/apimachinery/pkg/cache"
	"github.com/kcp-dev/logicalcluster"
	apiserverinternalv1alpha1 "k8s.io/api/apiserverinternal/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	apiserverinternalv1alpha1listers "k8s.io/client-go/listers/apiserverinternal/v1alpha1"
	"k8s.io/client-go/tools/cache"
)

var _ apiserverinternalv1alpha1listers.StorageVersionLister = &StorageVersionClusterLister{}

// StorageVersionClusterLister implements the apiserverinternalv1alpha1listers.StorageVersionLister interface.
type StorageVersionClusterLister struct {
	indexer cache.Indexer
}

// NewStorageVersionClusterLister returns a new StorageVersionClusterLister.
func NewStorageVersionClusterLister(indexer cache.Indexer) apiserverinternalv1alpha1listers.StorageVersionLister {
	return &StorageVersionClusterLister{indexer: indexer}
}

// List lists all apiserverinternalv1alpha1.StorageVersion in the indexer.
func (s StorageVersionClusterLister) List(selector labels.Selector) (ret []*apiserverinternalv1alpha1.StorageVersion, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*apiserverinternalv1alpha1.StorageVersion))
	})
	return ret, err
}

// Get retrieves the apiserverinternalv1alpha1.StorageVersion from the indexer for a given name.
func (s StorageVersionClusterLister) Get(name string) (*apiserverinternalv1alpha1.StorageVersion, error) {
	panic("Calling 'Get' is not supported before scoping lister to a workspace")
}

// Cluster returns an object that can list and get apiserverinternalv1alpha1.StorageVersion.

func (s StorageVersionClusterLister) Cluster(cluster logicalcluster.Name) apiserverinternalv1alpha1listers.StorageVersionLister {
	return &StorageVersionLister{indexer: s.indexer, cluster: cluster}
}

// StorageVersionLister implements the apiserverinternalv1alpha1listers.StorageVersionLister interface.
type StorageVersionLister struct {
	indexer cache.Indexer
	cluster logicalcluster.Name
}

// List lists all apiserverinternalv1alpha1.StorageVersion in the indexer.
func (s StorageVersionLister) List(selector labels.Selector) (ret []*apiserverinternalv1alpha1.StorageVersion, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*apiserverinternalv1alpha1.StorageVersion)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}

	return ret, err
}

// Get retrieves the apiserverinternalv1alpha1.StorageVersion from the indexer for a given name.
func (s StorageVersionLister) Get(name string) (*apiserverinternalv1alpha1.StorageVersion, error) {
	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(apiserverinternalv1alpha1.Resource("StorageVersion"), name)
	}
	return obj.(*apiserverinternalv1alpha1.StorageVersion), nil
}
