//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1beta1

import (
	apimachinerycache "github.com/kcp-dev/apimachinery/pkg/cache"
	"github.com/kcp-dev/logicalcluster"
	nodev1beta1 "k8s.io/api/node/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	nodev1beta1listers "k8s.io/client-go/listers/node/v1beta1"
	"k8s.io/client-go/tools/cache"
)

var _ nodev1beta1listers.RuntimeClassLister = &RuntimeClassClusterLister{}

// RuntimeClassClusterLister implements the nodev1beta1listers.RuntimeClassLister interface.
type RuntimeClassClusterLister struct {
	indexer cache.Indexer
}

// NewRuntimeClassClusterLister returns a new RuntimeClassClusterLister.
func NewRuntimeClassClusterLister(indexer cache.Indexer) nodev1beta1listers.RuntimeClassLister {
	return &RuntimeClassClusterLister{indexer: indexer}
}

// List lists all nodev1beta1.RuntimeClass in the indexer.
func (s RuntimeClassClusterLister) List(selector labels.Selector) (ret []*nodev1beta1.RuntimeClass, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*nodev1beta1.RuntimeClass))
	})
	return ret, err
}

// Get retrieves the nodev1beta1.RuntimeClass from the indexer for a given name.
func (s RuntimeClassClusterLister) Get(name string) (*nodev1beta1.RuntimeClass, error) {
	panic("Calling 'Get' is not supported before scoping lister to a workspace")
}

// Cluster returns an object that can list and get nodev1beta1.RuntimeClass.

func (s RuntimeClassClusterLister) Cluster(cluster logicalcluster.Name) nodev1beta1listers.RuntimeClassLister {
	return &RuntimeClassLister{indexer: s.indexer, cluster: cluster}
}

// RuntimeClassLister implements the nodev1beta1listers.RuntimeClassLister interface.
type RuntimeClassLister struct {
	indexer cache.Indexer
	cluster logicalcluster.Name
}

// List lists all nodev1beta1.RuntimeClass in the indexer.
func (s RuntimeClassLister) List(selector labels.Selector) (ret []*nodev1beta1.RuntimeClass, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*nodev1beta1.RuntimeClass)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}

	return ret, err
}

// Get retrieves the nodev1beta1.RuntimeClass from the indexer for a given name.
func (s RuntimeClassLister) Get(name string) (*nodev1beta1.RuntimeClass, error) {
	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(nodev1beta1.Resource("RuntimeClass"), name)
	}
	return obj.(*nodev1beta1.RuntimeClass), nil
}
