//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	apimachinerycache "github.com/kcp-dev/apimachinery/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v2"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	corev1listers "k8s.io/client-go/listers/core/v1"
	"k8s.io/client-go/tools/cache"
)

var _ corev1listers.ConfigMapLister = &ConfigMapClusterLister{}

// ConfigMapClusterLister implements the corev1listers.ConfigMapLister interface.
type ConfigMapClusterLister struct {
	indexer cache.Indexer
}

// NewConfigMapClusterLister returns a new ConfigMapClusterLister.
func NewConfigMapClusterLister(indexer cache.Indexer) corev1listers.ConfigMapLister {
	return &ConfigMapClusterLister{indexer: indexer}
}

// List lists all corev1.ConfigMap in the indexer.
func (s ConfigMapClusterLister) List(selector labels.Selector) (ret []*corev1.ConfigMap, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*corev1.ConfigMap))
	})
	return ret, err
}

// ConfigMaps returns an object that can list and get corev1.ConfigMap.
func (s ConfigMapClusterLister) ConfigMaps(namespace string) corev1listers.ConfigMapNamespaceLister {
	panic("Calling 'ConfigMaps' is not supported before scoping lister to a workspace")
}

// Cluster returns an object that can list and get corev1.ConfigMap.

func (s ConfigMapClusterLister) Cluster(cluster logicalcluster.Name) corev1listers.ConfigMapLister {
	return &ConfigMapLister{indexer: s.indexer, cluster: cluster}
}

// ConfigMapLister implements the corev1listers.ConfigMapLister interface.
type ConfigMapLister struct {
	indexer cache.Indexer
	cluster logicalcluster.Name
}

// List lists all corev1.ConfigMap in the indexer.
func (s ConfigMapLister) List(selector labels.Selector) (ret []*corev1.ConfigMap, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*corev1.ConfigMap)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}

	return ret, err
}

// ConfigMaps returns an object that can list and get corev1.ConfigMap.
func (s ConfigMapLister) ConfigMaps(namespace string) corev1listers.ConfigMapNamespaceLister {
	return &ConfigMapNamespaceLister{indexer: s.indexer, cluster: s.cluster, namespace: namespace}
}

// ConfigMapNamespaceLister implements the corev1listers.ConfigMapNamespaceLister interface.
type ConfigMapNamespaceLister struct {
	indexer   cache.Indexer
	cluster   logicalcluster.Name
	namespace string
}

// List lists all corev1.ConfigMap in the indexer for a given namespace.
func (s ConfigMapNamespaceLister) List(selector labels.Selector) (ret []*corev1.ConfigMap, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), s.namespace, "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterAndNamespaceIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*corev1.ConfigMap)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}
	return ret, err
}

// Get retrieves the corev1.ConfigMap from the indexer for a given namespace and name.
func (s ConfigMapNamespaceLister) Get(name string) (*corev1.ConfigMap, error) {
	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(corev1.Resource("ConfigMap"), name)
	}
	return obj.(*corev1.ConfigMap), nil
}
