//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	apimachinerycache "github.com/kcp-dev/apimachinery/pkg/cache"
	"github.com/kcp-dev/logicalcluster"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	corev1listers "k8s.io/client-go/listers/core/v1"
	"k8s.io/client-go/tools/cache"
)

var _ corev1listers.PersistentVolumeLister = &PersistentVolumeClusterLister{}

// PersistentVolumeClusterLister implements the corev1listers.PersistentVolumeLister interface.
type PersistentVolumeClusterLister struct {
	indexer cache.Indexer
}

// NewPersistentVolumeClusterLister returns a new PersistentVolumeClusterLister.
func NewPersistentVolumeClusterLister(indexer cache.Indexer) corev1listers.PersistentVolumeLister {
	return &PersistentVolumeClusterLister{indexer: indexer}
}

// List lists all corev1.PersistentVolume in the indexer.
func (s PersistentVolumeClusterLister) List(selector labels.Selector) (ret []*corev1.PersistentVolume, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*corev1.PersistentVolume))
	})
	return ret, err
}

// Get retrieves the corev1.PersistentVolume from the indexer for a given name.
func (s PersistentVolumeClusterLister) Get(name string) (*corev1.PersistentVolume, error) {
	panic("Calling 'Get' is not supported before scoping lister to a workspace")
}

// Cluster returns an object that can list and get corev1.PersistentVolume.

func (s PersistentVolumeClusterLister) Cluster(cluster logicalcluster.Name) corev1listers.PersistentVolumeLister {
	return &PersistentVolumeLister{indexer: s.indexer, cluster: cluster}
}

// PersistentVolumeLister implements the corev1listers.PersistentVolumeLister interface.
type PersistentVolumeLister struct {
	indexer cache.Indexer
	cluster logicalcluster.Name
}

// List lists all corev1.PersistentVolume in the indexer.
func (s PersistentVolumeLister) List(selector labels.Selector) (ret []*corev1.PersistentVolume, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*corev1.PersistentVolume)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}

	return ret, err
}

// Get retrieves the corev1.PersistentVolume from the indexer for a given name.
func (s PersistentVolumeLister) Get(name string) (*corev1.PersistentVolume, error) {
	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(corev1.Resource("PersistentVolume"), name)
	}
	return obj.(*corev1.PersistentVolume), nil
}
