//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	apimachinerycache "github.com/kcp-dev/apimachinery/pkg/cache"
	"github.com/kcp-dev/logicalcluster"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	corev1listers "k8s.io/client-go/listers/core/v1"
	"k8s.io/client-go/tools/cache"
)

var _ corev1listers.ServiceAccountLister = &ServiceAccountClusterLister{}

// ServiceAccountClusterLister implements the corev1listers.ServiceAccountLister interface.
type ServiceAccountClusterLister struct {
	indexer cache.Indexer
}

// NewServiceAccountClusterLister returns a new ServiceAccountClusterLister.
func NewServiceAccountClusterLister(indexer cache.Indexer) corev1listers.ServiceAccountLister {
	return &ServiceAccountClusterLister{indexer: indexer}
}

// List lists all corev1.ServiceAccount in the indexer.
func (s ServiceAccountClusterLister) List(selector labels.Selector) (ret []*corev1.ServiceAccount, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*corev1.ServiceAccount))
	})
	return ret, err
}

// ServiceAccounts returns an object that can list and get corev1.ServiceAccount.
func (s ServiceAccountClusterLister) ServiceAccounts(namespace string) corev1listers.ServiceAccountNamespaceLister {
	panic("Calling 'ServiceAccounts' is not supported before scoping lister to a workspace")
}

// Cluster returns an object that can list and get corev1.ServiceAccount.

func (s ServiceAccountClusterLister) Cluster(cluster logicalcluster.Name) corev1listers.ServiceAccountLister {
	return &ServiceAccountLister{indexer: s.indexer, cluster: cluster}
}

// ServiceAccountLister implements the corev1listers.ServiceAccountLister interface.
type ServiceAccountLister struct {
	indexer cache.Indexer
	cluster logicalcluster.Name
}

// List lists all corev1.ServiceAccount in the indexer.
func (s ServiceAccountLister) List(selector labels.Selector) (ret []*corev1.ServiceAccount, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*corev1.ServiceAccount)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}

	return ret, err
}

// ServiceAccounts returns an object that can list and get corev1.ServiceAccount.
func (s ServiceAccountLister) ServiceAccounts(namespace string) corev1listers.ServiceAccountNamespaceLister {
	return &ServiceAccountNamespaceLister{indexer: s.indexer, cluster: s.cluster, namespace: namespace}
}

// ServiceAccountNamespaceLister implements the corev1listers.ServiceAccountNamespaceLister interface.
type ServiceAccountNamespaceLister struct {
	indexer   cache.Indexer
	cluster   logicalcluster.Name
	namespace string
}

// List lists all corev1.ServiceAccount in the indexer for a given namespace.
func (s ServiceAccountNamespaceLister) List(selector labels.Selector) (ret []*corev1.ServiceAccount, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), s.namespace, "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterAndNamespaceIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*corev1.ServiceAccount)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}
	return ret, err
}

// Get retrieves the corev1.ServiceAccount from the indexer for a given namespace and name.
func (s ServiceAccountNamespaceLister) Get(name string) (*corev1.ServiceAccount, error) {
	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(corev1.Resource("ServiceAccount"), name)
	}
	return obj.(*corev1.ServiceAccount), nil
}
