//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	apimachinerycache "github.com/kcp-dev/apimachinery/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v2"
	storagev1 "k8s.io/api/storage/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	storagev1listers "k8s.io/client-go/listers/storage/v1"
	"k8s.io/client-go/tools/cache"
)

var _ storagev1listers.CSIDriverLister = &CSIDriverClusterLister{}

// CSIDriverClusterLister implements the storagev1listers.CSIDriverLister interface.
type CSIDriverClusterLister struct {
	indexer cache.Indexer
}

// NewCSIDriverClusterLister returns a new CSIDriverClusterLister.
func NewCSIDriverClusterLister(indexer cache.Indexer) storagev1listers.CSIDriverLister {
	return &CSIDriverClusterLister{indexer: indexer}
}

// List lists all storagev1.CSIDriver in the indexer.
func (s CSIDriverClusterLister) List(selector labels.Selector) (ret []*storagev1.CSIDriver, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*storagev1.CSIDriver))
	})
	return ret, err
}

// Get retrieves the storagev1.CSIDriver from the indexer for a given name.
func (s CSIDriverClusterLister) Get(name string) (*storagev1.CSIDriver, error) {
	panic("Calling 'Get' is not supported before scoping lister to a workspace")
}

// Cluster returns an object that can list and get storagev1.CSIDriver.

func (s CSIDriverClusterLister) Cluster(cluster logicalcluster.Name) storagev1listers.CSIDriverLister {
	return &CSIDriverLister{indexer: s.indexer, cluster: cluster}
}

// CSIDriverLister implements the storagev1listers.CSIDriverLister interface.
type CSIDriverLister struct {
	indexer cache.Indexer
	cluster logicalcluster.Name
}

// List lists all storagev1.CSIDriver in the indexer.
func (s CSIDriverLister) List(selector labels.Selector) (ret []*storagev1.CSIDriver, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*storagev1.CSIDriver)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}

	return ret, err
}

// Get retrieves the storagev1.CSIDriver from the indexer for a given name.
func (s CSIDriverLister) Get(name string) (*storagev1.CSIDriver, error) {
	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(storagev1.Resource("CSIDriver"), name)
	}
	return obj.(*storagev1.CSIDriver), nil
}
