//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1beta1

import (
	apimachinerycache "github.com/kcp-dev/apimachinery/pkg/cache"
	"github.com/kcp-dev/logicalcluster"
	admissionregistrationv1beta1 "k8s.io/api/admissionregistration/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	admissionregistrationv1beta1listers "k8s.io/client-go/listers/admissionregistration/v1beta1"
	"k8s.io/client-go/tools/cache"
)

var _ admissionregistrationv1beta1listers.MutatingWebhookConfigurationLister = &MutatingWebhookConfigurationClusterLister{}

// MutatingWebhookConfigurationClusterLister implements the admissionregistrationv1beta1listers.MutatingWebhookConfigurationLister interface.
type MutatingWebhookConfigurationClusterLister struct {
	indexer cache.Indexer
}

// NewMutatingWebhookConfigurationClusterLister returns a new MutatingWebhookConfigurationClusterLister.
func NewMutatingWebhookConfigurationClusterLister(indexer cache.Indexer) admissionregistrationv1beta1listers.MutatingWebhookConfigurationLister {
	return &MutatingWebhookConfigurationClusterLister{indexer: indexer}
}

// List lists all admissionregistrationv1beta1.MutatingWebhookConfiguration in the indexer.
func (s MutatingWebhookConfigurationClusterLister) List(selector labels.Selector) (ret []*admissionregistrationv1beta1.MutatingWebhookConfiguration, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*admissionregistrationv1beta1.MutatingWebhookConfiguration))
	})
	return ret, err
}

// Get retrieves the admissionregistrationv1beta1.MutatingWebhookConfiguration from the indexer for a given name.
func (s MutatingWebhookConfigurationClusterLister) Get(name string) (*admissionregistrationv1beta1.MutatingWebhookConfiguration, error) {
	panic("Calling 'Get' is not supported before scoping lister to a workspace")
}

// Cluster returns an object that can list and get admissionregistrationv1beta1.MutatingWebhookConfiguration.

func (s MutatingWebhookConfigurationClusterLister) Cluster(cluster logicalcluster.Name) admissionregistrationv1beta1listers.MutatingWebhookConfigurationLister {
	return &MutatingWebhookConfigurationLister{indexer: s.indexer, cluster: cluster}
}

// MutatingWebhookConfigurationLister implements the admissionregistrationv1beta1listers.MutatingWebhookConfigurationLister interface.
type MutatingWebhookConfigurationLister struct {
	indexer cache.Indexer
	cluster logicalcluster.Name
}

// List lists all admissionregistrationv1beta1.MutatingWebhookConfiguration in the indexer.
func (s MutatingWebhookConfigurationLister) List(selector labels.Selector) (ret []*admissionregistrationv1beta1.MutatingWebhookConfiguration, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*admissionregistrationv1beta1.MutatingWebhookConfiguration)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}

	return ret, err
}

// Get retrieves the admissionregistrationv1beta1.MutatingWebhookConfiguration from the indexer for a given name.
func (s MutatingWebhookConfigurationLister) Get(name string) (*admissionregistrationv1beta1.MutatingWebhookConfiguration, error) {
	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(admissionregistrationv1beta1.Resource("MutatingWebhookConfiguration"), name)
	}
	return obj.(*admissionregistrationv1beta1.MutatingWebhookConfiguration), nil
}
