//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1

import (
	apimachinerycache "github.com/kcp-dev/apimachinery/pkg/cache"
	"github.com/kcp-dev/logicalcluster"
	networkingv1 "k8s.io/api/networking/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	networkingv1listers "k8s.io/client-go/listers/networking/v1"
	"k8s.io/client-go/tools/cache"
)

var _ networkingv1listers.NetworkPolicyLister = &NetworkPolicyClusterLister{}

// NetworkPolicyClusterLister implements the networkingv1listers.NetworkPolicyLister interface.
type NetworkPolicyClusterLister struct {
	indexer cache.Indexer
}

// NewNetworkPolicyClusterLister returns a new NetworkPolicyClusterLister.
func NewNetworkPolicyClusterLister(indexer cache.Indexer) networkingv1listers.NetworkPolicyLister {
	return &NetworkPolicyClusterLister{indexer: indexer}
}

// List lists all networkingv1.NetworkPolicy in the indexer.
func (s NetworkPolicyClusterLister) List(selector labels.Selector) (ret []*networkingv1.NetworkPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*networkingv1.NetworkPolicy))
	})
	return ret, err
}

// NetworkPolicies returns an object that can list and get networkingv1.NetworkPolicy.
func (s NetworkPolicyClusterLister) NetworkPolicies(namespace string) networkingv1listers.NetworkPolicyNamespaceLister {
	panic("Calling 'NetworkPolicies' is not supported before scoping lister to a workspace")
}

// Cluster returns an object that can list and get networkingv1.NetworkPolicy.

func (s NetworkPolicyClusterLister) Cluster(cluster logicalcluster.Name) networkingv1listers.NetworkPolicyLister {
	return &NetworkPolicyLister{indexer: s.indexer, cluster: cluster}
}

// NetworkPolicyLister implements the networkingv1listers.NetworkPolicyLister interface.
type NetworkPolicyLister struct {
	indexer cache.Indexer
	cluster logicalcluster.Name
}

// List lists all networkingv1.NetworkPolicy in the indexer.
func (s NetworkPolicyLister) List(selector labels.Selector) (ret []*networkingv1.NetworkPolicy, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), "", "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*networkingv1.NetworkPolicy)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}

	return ret, err
}

// NetworkPolicies returns an object that can list and get networkingv1.NetworkPolicy.
func (s NetworkPolicyLister) NetworkPolicies(namespace string) networkingv1listers.NetworkPolicyNamespaceLister {
	return &NetworkPolicyNamespaceLister{indexer: s.indexer, cluster: s.cluster, namespace: namespace}
}

// NetworkPolicyNamespaceLister implements the networkingv1listers.NetworkPolicyNamespaceLister interface.
type NetworkPolicyNamespaceLister struct {
	indexer   cache.Indexer
	cluster   logicalcluster.Name
	namespace string
}

// List lists all networkingv1.NetworkPolicy in the indexer for a given namespace.
func (s NetworkPolicyNamespaceLister) List(selector labels.Selector) (ret []*networkingv1.NetworkPolicy, err error) {
	selectAll := selector == nil || selector.Empty()

	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), s.namespace, "")
	list, err := s.indexer.ByIndex(apimachinerycache.ClusterAndNamespaceIndexName, key)
	if err != nil {
		return nil, err
	}

	for i := range list {
		obj := list[i].(*networkingv1.NetworkPolicy)
		if selectAll {
			ret = append(ret, obj)
		} else {
			if selector.Matches(labels.Set(obj.GetLabels())) {
				ret = append(ret, obj)
			}
		}
	}
	return ret, err
}

// Get retrieves the networkingv1.NetworkPolicy from the indexer for a given namespace and name.
func (s NetworkPolicyNamespaceLister) Get(name string) (*networkingv1.NetworkPolicy, error) {
	key := apimachinerycache.ToClusterAwareKey(s.cluster.String(), s.namespace, name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(networkingv1.Resource("NetworkPolicy"), name)
	}
	return obj.(*networkingv1.NetworkPolicy), nil
}
